<br />
<h2>Current menus</h2>
<br />
<?php
if ($this->menus != null){
 ?>
 <table class="spreadsheet" cellpadding="0" cellspacing="0">
        <tr>
            <th>Links</th>
            <th>Menu name</th>
        </tr>   
 <?php
    echo $this->partialLoop('partials/_menu-row.phtml', $this->menus);
}else{
    echo "<p>you dont have any menu yet</p>";
}
 ?>
 </table>
<p><a href="/menu/create">Create a new menu</a></p>