<h2>Search Results</h2>

<?php
if(is_array($this->results) && count($this->results)>0){
?>
<p>Your search for <em><?php echo $this->keywords ?></em> returned <b><?php echo count($this->results) ?></b> results</p>

<?php
foreach ($this->results as $result) {
?>
<h3><a href="/page/open/id/ <?php echo $result->page_id ?>"> <?php echo $result->page_headline ?></a></h3>
<p> <?php echo $result->page_description ?></p>
<?php
/*
	echo "<pre>";
    var_dump($result);
    echo "</pre>";
    echo "***************************************************************<br>";
    echo "***************************************************************";

  */
 }
    
}else{
?>
<p>your search for <b><?php echo $this->keywords ?> </b>returned no results</p>
<?php    
}
?>