<?php
if ($this->page_id > 0){
    $page = new CMS_Content_Item_Page($this->page_id);
    $pageName = $page->name;
}else{
    $pageName=null;
}
?>
<tr>
    <td class="links">
        <a href="/menuitem/update/id/ <?php echo $this->id; ?>">update</a> |
        <a href="/menuitem/move/direction/up/id/ <?php echo $this->id; ?>">move up</a> |
        <a href="/menuitem/move/direction/down/id/ <?php echo $this->id; ?>">move down</a> |
        <a href="/menuitem/delete/id/ <?php echo $this->id; ?>">delete</a> |
    </td>
    <td>
        <?php echo $this->label; ?>
    </td>
    <td>
        <?php echo $pageName; ?>
    </td>
    <td>
        <?php echo $this->link; ?>
    </td>
</tr>