<?php
if($this->pageCount){
	//you need to add each of the request parameters to url
	$params=Zend_Controller_Front::getInstance()->getRequest()->getParams();
	
	//remove the system parameters
	unset($params['module']);
	unset($params['controller']);
	unset($params['action']);

}
?>

<div class="paginationControl">

<!-- Previous page link -->
<?php if (isset($this->previous)){ ?>
<a href="<?php echo $this->url(array_merge($params, array('page'=>$this->previous)));?>">
&lt; Previous
</a>|
<?php }else {?>
<span class="disabled">&lt; Previous </span>
<?php } ?>

<!-- Numbered page links-->
<?php foreach($this->pagesInRange as $page){ ?>
	<?php if($this->current != $page) {?>
		<a href="<?php echo $this->url(array_merge($params, array('page'=>$page)));?>"> <?php echo $page ?> |</a>
	<?php } else {?> <!-- if close, else start --> 
		<?php echo $page?>
	<?php } ?> <!-- else close -->
<?php } ?> <!-- foreach close -->

<!-- Next page links-->
<?php if(isset($this->next)){ ?>
	<a href="<?php echo $this->url(array_merge($params, array('page'=>$this->next)));?>"> &gt; Next |</a>
<?php } else{ ?>
	<span class="disabled">&gt; Next </span>
<?php } ?>
?>
 </div>